version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    networks: 
      - mynet
    volumes: 
      - myvol:/myvol
    
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    networks: 
      - mynet
    volumes: 
      - myvol:/myvol
    ports:
      - "8080:80"
    
networks:
  mynet:
    driver: bridge
    
volumes:
  myvol:
