version: '3'

services:
  mongo:
    image: mongo:latest
    networks: 
      - mynet
    volumes: 
      - myvol:/myvol
    
  mongo-express:
    image: mongo-express:latest
    networks: 
      - mynet
    volumes: 
      - myvol:/myvol
    
networks:
  mynet:
    driver: bridge
    
volumes:
  myvol
